### ISSUE TITLE
[Bug] AZ doesn't currently work with VIZ Extension

### ISSUE THREAD

**Issue by japzone1** [az4521/TachiyomiAZ#103]
### Device information
* Tachiyomi version: v8.8.1-AZ
* Android version: 14
* Device: Asus ROG Phone 6

## Steps to reproduce
1. Install VIZ extension 
2. Browse for a manga and try to open a chapter 

### Expected behavior
Pages should load. 

### Actual behavior
Pages don't load. 

### Other details
Pages load fine in normal Mihon. Already tried reporting to the extension repo, but they said it was an app issue and closed it.

**Comment by japzone1** [comment]
Ok, did more testing, and it's actually only with certain chapters instead of the all like I originally assumed. I just had bad RNG somehow trying only broken chapters. Chapters causing consistent issues for testing are Ruri Chapter 1 and Dandadan Chapter 1. Ruri chapter 22 loads fine if you need something to compare with.

**Comment by az4521** [comment]
try the dev build
https://crafty.moe/tachiyomiAZ.apk
the current release has an issue with some json stuff
lmk if it works

**Comment by japzone1** [comment]
> try the dev build https://crafty.moe/tachiyomiAZ.apk the current release has an issue with some json stuff lmk if it works

Installed the APK and didn't get any install errors, but version is still displayed as v8.8.1-AZ, so not sure if I was already on the dev build or it didn't install somehow. 

Tested the above chapters again and they still fail on loading. 

Attached a logcat just in case it's useful. 
[log-tachiaz_2024_10_06_23_51_48.log](https://github.com/user-attachments/files/17272540/log-tachiaz_2024_10_06_23_51_48.log)

**Comment by az4521** [comment]
the version should still be the same after updating, all that changes in dev builds is the build time under settings -> about

i've made another dev build that should resolve the error, fixed in https://github.com/az4521/TachiyomiAZ/commit/2167a8f6c82482d6b5774e8e7bb8d07d2a94c657

you can download the new dev build at the same URL, https://crafty.moe/tachiyomiAZ.apk
