### ISSUE TITLE
[Bug] EX-hentai doesn't work

### ISSUE THREAD

**Issue by RsReez** [az4521/TachiyomiAZ#105]
I acknowledge that:

- I have updated to the latest version of the app (stable is v8.7.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 8.8.1
* Android version: 14
* Device: Samsung tab S10 ultra

## Steps to reproduce
1. First step: open ex-hentai
2. Second step: try to open any chapter of any hentai.

### Expected behavior
Chapter opens, can read hentai.

### Actual behavior
Opens black screen with loading wheel, kicks back to chapter selection after a second,  saying "page list empty".

### Other details
Was working fine earlier.

**Comment by BelfastC35** [comment]
Same issue here, downloaded chapters work fine on sadpanda, but anything not downloaded returns a "page list empty" error. Age of the gallery doesn't seem to matter

**Comment by Dmograine** [comment]
I have visited the panda website and it seems they have changed the way the "pages" work on the galleries now, for some reason. Only reason i can think of for this specific type of error.

Hopefully it is a simple fix and the app hasn't been abandoned like tachi itself.

**Comment by Dmograine** [comment]
I visited the panda website and it would seem they have changed the way the "pages" of the galleries are displayed, and probably due to this the app is now unable to recognize them as pages and gives the error, as now it sees the galleries as empty.

Hopefully it will be an easy fix.
Hopefully.

**Comment by uNderdog101** [comment]
This issue affected both EhViewer and JHenTai and both of those apps updated pretty much instantly, so the fix seems pretty simple.

**Comment by az4521** [comment]
https://github.com/az4521/TachiyomiAZ/commit/b84a2b3e40dc15a6397a1c687a1ee4d6100c751a 
release soon™

**Comment by BelfastC35** [comment]
thanks for the quick fix love you my guy
