### ISSUE TITLE
Fix Android Studio sync / build or provide build instruction.

### ISSUE THREAD

**Issue by QuentinLB** [az4521/TachiyomiAZ#109]
Hi, I was looking to debug the app to fix [my issue](https://github.com/az4521/TachiyomiAZ/issues/108), but I'm unable to build the app. 

- Many dependencies failed to resolve (old tachi deps, jcenter deps, etc.)
   - By disabling the shortcut helper plugin I can try syncing but then it fail to resolves 
   
![photo_2024-11-11_14-03-21](https://github.com/user-attachments/assets/052350c8-626e-43b7-ae38-6b1da9a71de8)

- AGP upgrade doesn't work (seems that the upgrade assistant is unable to find AGP version in build files). 

How to reproduce : 
- Clone TachiAZ
- Open it in Android Studio
- Try to sync project (fail)

I understand that this project is under low maintenance given the drift with the mainline. But it's the only tachi fork that truly support older devices and provide good features like proper language filtering from extensions and saving filters. I'm willing to spend time to at least fix the issues I encounter while using it and provided pull requests but I'm unable to since I can't get it to build. 

Have a great day.

**Comment by abdlhay** [comment]
You can replace the unresolved dependencies with the following:

- **`org.tachiyomi:source-api:1.1`**  
- **`uy.kohesive.injekt:injekt-core:1.16.1`**

For **FlexibleAdapter**, you'll need to add the module manually from its repository:  
[[FlexibleAdapter on GitHub](https://github.com/davideas/FlexibleAdapter)](https://github.com/davideas/FlexibleAdapter).

Regarding the other unresolved dependencies, I’m not familiar with them as I don’t use them in my project. However, I recommend checking other Tachiyomi forks to see which versions they are using. You might find the latest compatible versions there.

**Comment by QuentinLB** [comment]
Thanks a lot @az4521 !
