### ISSUE TITLE
[Bug] nhentai won't open chapters

### ISSUE THREAD

**Issue by doragonasdfghjkl** [az4521/TachiyomiAZ#110]
### Device information
* Tachiyomi version: 8.8.2
* Android version: 14
* Device: Nothing Phone (1)

## Steps to reproduce
1. go to nhentai extension
2. Open any doujin chapter
### Expected behavior
It should load chapters.

### Actual behavior
Kicks me out back to chapter selection screen.

### Other details
Doesn't show any errors, only small black box
Everything works when opened in web-view. Old doujins that I added into the library work fine.

recording:
https://github.com/user-attachments/assets/0884fe0c-3e1d-48a7-94e3-32f816b059a1

**Comment by az4521** [comment]
fixed in the dev build
https://github.com/az4521/TachiyomiAZ/commit/839056a959a69610d4611d56a64160f86f7aa727

get it here  
https://crafty.moe/tachiyomiAZ.apk
