### ISSUE TITLE
[Bug] EX-hentai doesn't work electric boogaloo

### ISSUE THREAD

**Issue by rakosi2** [az4521/TachiyomiAZ#112]
### Device information
* Tachiyomi version: v8.8.2-AZ
* Android version: 14
* Device: OP7P

## Steps to reproduce
1. Open TachiyomiAZ
2. Try to open EXH

### Expected behavior
EXH to open

### Actual behavior
"No results found"

### Other details
Similar to #105 but that was for the chapters, this time it is the browser.
Have verified that I can access EXH on PC

**Comment by az4521** [comment]
have you tried logging out and back in? exh recently made a change that invalidated old cookies

**Comment by rakosi2** [comment]
Ah, that has fixed it. Maybe AZ should invalidate old cookies.
