### ISSUE TITLE
Hcaptcha verification in loop

### ISSUE THREAD

**Issue by fam007e** [az4521/TachiyomiAZ#44]
### Device information
* Tachiyomi version: V8.7.1-AZ
* Android version: 11
* Device: Realme Narzo 50i

## Steps to reproduce
1. Open allporncomic extension in WebView 
2. Hcaptcha verification

### Expected behavior
Verification succeed and opens the website in WebView and then the extension browse option can excess the info inside the app. 

### Actual behavior
Hcaptcha verification occurs but it returns to hcaptcha verification. It does not open the website in WebView i.e. the verification is unsuccessful. 

### Other details
Also the search option in this extension also need the website's "old search" integrated as the new search option produce truncated results of only 20 comics.
I mentioned the hcaptcha problem in the extension page of tachiyomi, they said the tachiyomi app has resolved this issues but apparently it's only prevalent in tachiyomi-AZ only.
Therefore I am mentioning it here.

**Comment by az4521** [comment]
somehow this issue has magically fixed itself and i can't get it to happen again
