### ISSUE TITLE
Can you update the version of ehentai manga with auto update?

### ISSUE THREAD

**Issue by AwesomeQuest** [az4521/TachiyomiAZ#45]
### Device information
* Tachiyomi version: 8.7.1-AZ
* Android version: 12
* Device: Samsung Galaxy A72

Hi, I love the feature where you can update the version of an ehentai manga and gett the latest pages, but that doesn't happen with global update and you need to update manually. Is there a setting I'm missing?

**Comment by az4521** [comment]
there is a setting

settings -> ehentai -> gallery update checker (way at the bottom) -> time between update batches

they're excluded from the global update because you'd get IP banned
