### ISSUE TITLE
[Bug] NHentai is inaccessible

### ISSUE THREAD

**Issue by chichibooxd** [az4521/TachiyomiAZ#46]
### Device information
* Tachiyomi version: 8.7.1-AZ
* Android version: 11
* Device: Vivo Y11

## Steps to reproduce
1. Browse Nhentai
2. Open in webview

### Expected behavior
Cloudflare will confirm that the connection is secure and proceed to the site

### Actual behavior
Stuck in a loop of confirmation and keeps refreshing.

### Other details
Same issue happened before because of Nhentai enabling cloudflare protection.

**Comment by az4521** [comment]
if you get the dev build, you can change the user agent in settings -> advanced. setting it to
```
Mozilla/5.0 (X11; U; Linux armv7l like Android; en-us) AppleWebKit/531.2+ (KHTML, like Gecko) Version/5.0 Safari/533.2+ Kindle/3.0+
```
seems to fix it

**Comment by chichibooxd** [comment]
Reopening. The issue is back again for a few weeks now.

I'm currently using 8.7.4-AZ on the same phone.

**Comment by TheGershon** [comment]
This is still an issue on the latest dev build, even when bypassing the built-in nhentai extension for the latest from keiyoshi's repo (tried both). Already tried installing certificates and the custom user-agemt above from above.
