### ISSUE TITLE
ehentai not checking galleries 

### ISSUE THREAD

**Issue by AwesomeQuest** [az4521/TachiyomiAZ#48]
### Device information
Tachiyomi version: 8.7.1-AZ
Android version: 12 (SDK 31)
Android build ID: SP1A.210812.016.A725FXXU4BVG1
Device brand: samsung
Device manufacturer: samsung
Device name: a72q
Device model: SM-A725F
Device product name: a72qnseea

## Steps to reproduce
I have turned off all bettery optimizations for the app but the galleries never update, the updater statistics say that they ran X minutes ago but didn't check anything. I've tried setting the frequency to 1 hour and staying on the app for that hour as well as 12 and 24 hours and waited several days. No galleries checked. I go and update manually and there are updates available 

## Issue/Request
The app simply isn't checking ehentai.
Maybe add a setting to include ehentai in normal global update?

**Comment by az4521** [comment]
including eh/exh in the normal global update would get you IP banned near instantly. try going into settings -> advanced -> open debug menu and using the "reset aged flag in ex hmanga" option, then "test launch ehentai background updater", then "reschedule ehentai background updater". be sure not to touch anything else in there
