### ISSUE TITLE
Failed to Bypass Cloudflare on Built-in NHentai plugin.

### ISSUE THREAD

**Issue by MikaelaMuller** [az4521/TachiyomiAZ#49]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v8.7.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: v8.7.1-AZ
* Android version: 12
* Device: Samsung Galaxy A5 2017

## Steps to reproduce
1. Open App
2. Try to Open NHentai

### Expected behavior
You get to see the *ahem* stuff, Read manga 

### Actual behavior
java.lang.exception Failed to Bypass cloudflare

### Other details
Additional details and attachments.
https://nhentai.net/g/125582/
This is what im trying to read if that's important
Device is running on a custom rom (LineageOS 19.1)
I followed troubleshotting guides, didn't work
Might be because of User agent, Other Tachyforks have made people able to change User agents which fixed this.

**Comment by az4521** [comment]
#46
