### ISSUE TITLE
I can't restore backup from tachiyomi.

### ISSUE THREAD

**Issue by reeocity** [az4521/TachiyomiAZ#50]
## # Device information
* Tachiyomi version: 0.8.72az
* Android version: 5.1.1
* Device: Samsung galaxy tab 4

## Steps to reproduce
1. Go to settings 2. Click backup 3. Click restore backup 4. Only showing Dropbox and sound picker.                                         ## Issue/Request
I am supposed to be able to pick any file from file Manger 

## Other details
Additional details and attachments.
![image](https://user-images.githubusercontent.com/26421959/189461208-b86fbdbf-a510-4900-8ccc-a70a2dac6ce9.jpg)

**Comment by reeocity** [comment]
Please it is not completed

**Comment by az4521** [comment]
ah you edited it to actually add the issue, great

**Comment by reeocity** [comment]
Thank you

**Comment by reeocity** [comment]
Fixed

**Comment by az4521** [comment]
how

**Comment by reeocity** [comment]
I downloaded a file manager that allowed root access.
So the file manager showed up when I wanted to restore.
It took me to the root directory first.
Then I navigate to storage/emulated/0/tachiyomi 
Which is where I saves the backup 
I was using my default phone file manager before

Thank you very much for creating this app
I couldn't update my tachiyomi anymore on my phone as the device is an old device.
And I only keep the android because of tachiyomi
