### ISSUE TITLE
No more than 25 titles are loaded on exhentai.

### ISSUE THREAD

**Issue by kii-work** [az4521/TachiyomiAZ#52]
No more than 25 titles are loaded on exhentai. If you immediately go to the source, or do a tag search, the result is the same.
---

### Device information
* Tachiyomi version: 8.7.2
* Android version: 7
* Device: Honor 9

## Steps to reproduce
1. Open exhentai source
2. Scroll down
### Expected behavior
When you scroll down, new titles should load.

### Actual behavior
When you scroll down, new titles don't load. 

### Other details
It starts 01-02.11.22.

**Comment by az4521** [comment]
Fixed in the dev build
https://crafty.moe/tachiyomiAZ.apk
