### ISSUE TITLE
[Bug] EXhentai only shows first 25 results

### ISSUE THREAD

**Issue by grantA1025** [az4521/TachiyomiAZ#56]
### Device information
* Tachiyomi version: 8.7.2-AZ
* Android version: 10
* Device: Note 9

## Steps to reproduce
1. check ex hentai library
2. scroll down

### Expected behavior
more results should load

### Actual behavior
it stops loading new results

### Other details
I'm unsure if deliberate or a bug. I genuinely don't know and apologies if this is in the wrong place but it didn't happen until i just updated.

**Comment by archindivide** [comment]
Seems to impact all versions of Tachiyomi that work with exhentai, other sites do load additional results.

**Comment by archindivide** [comment]
Tested this build and it seems to resolve the issue https://github.com/az4521/TachiyomiAZ/issues/55#issuecomment-1304598999

**Comment by The7thSage** [comment]
> Tested this build and it seems to resolve the issue [#55 (comment)](https://github.com/az4521/TachiyomiAZ/issues/55#issuecomment-1304598999)
does anyone have the dev build I built my own version of most recent Github but ill have to uninstall my orig before even testing
