### ISSUE TITLE
UNDO

### ISSUE THREAD

**Issue by Jenmaq13** [az4521/TachiyomiAZ#58]
Hi! I'm a user! First of all thank you for your efforts to make this app!!! I have a suggestion that it should have an "UNDO" . Coz just like what happened today I accidentally deleted the downloaded chapters. The frustration that I have to go back home to connect to wifi and download it again. 😅😢🙈 Thank you again guys!!! Good job!! ❤ btw Im using the tachiyomi preview version r491.

**Comment by az4521** [comment]
this is tachiyomiAZ, not tachiyomi. you should head over to inorichi/tachiyomi
