### ISSUE TITLE
bug open source

### ISSUE THREAD

**Issue by kolinrno** [az4521/TachiyomiAZ#67]
**TOLONG BACA INI**

Saya mengakui bahwa:

- Saya telah memperbarui aplikasi ke versi terbaru (stabil adalah v8.7.0)
- Saya telah memperbarui semua ekstensi
- sebagian eksistensi populer tidak bisa di akses seperti DoujinDesu , sekai komik , dan mangasusu , boosei . ini beneran memggangu . tolong untuk fix update . and stay android 5.0 :D . thankkss!!

**Comment by az4521** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues
