### ISSUE TITLE
bug browser expired . no support [Bug] Write short description here

### ISSUE THREAD

**Issue by kolinrno** [az4521/TachiyomiAZ#68]
**PLEASE READ THIS**

I acknowledge that:

- I have updated to the latest version of the app (stable is v8.7.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

**DELETE THIS SECTION IF YOU HAVE READ AND ACKNOWLEDGED IT**

---

### Device information
* Tachiyomi version: new version
* Android version: 5.0
* Device: oppo
![Screenshot_2023-02-12-05-44-48-16](https://user-images.githubusercontent.com/120464340/218284307-d8c3f87f-3525-4cb5-bbb7-15a5b0ebb5fb.png)
 plis fixed . komikcast "403 http"

## Steps to reproduce
1. First step
2. Second step

### Expected behavior
This should happen.

### Actual behavior
This happened instead.

### Other details
Additional details and attachments.

**Comment by az4521** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues
