### ISSUE TITLE
[Bug] Sources/Extensions not showing on TachiyomiAZ

### ISSUE THREAD

**Issue by EmnMtz** [az4521/TachiyomiAZ#69]
### Device information
* Tachiyomi version: v8.7.3-AZ
* Android version: 11
* Device: realme 5 pro

## Steps to reproduce
1. update extensions via tachiyomi
2. check extensions on tachiyomiaz 

## Issue/Request
issue: sources/extensions on tachiyomiaz disappeared upon updating via tachiyomi

## Other details
Additional details and attachments.
- have both regular tachiyomi and tachiyomiaz installed. 
- extension updates available on tachiyomi 
- updated extensions and confirmed working on tachiyomi
- opened tachiyomiaz and prompted that source for manga not installed
- check extensions and nothing displayed

![Screenshot_2023-02-12-09-09-43-60_855c71507a0c11b360d5d38f8d2d1c96](https://user-images.githubusercontent.com/86273850/218288021-9e7fb573-70e4-4200-9e8d-0770cf2c479f.jpg)
![Screenshot_2023-02-12-09-08-23-23_855c71507a0c11b360d5d38f8d2d1c96](https://user-images.githubusercontent.com/86273850/218288024-7006e70d-796f-4665-85b1-cba055174b8c.jpg)
![Screenshot_2023-02-12-09-13-26-94_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/86273850/218288025-fd9abcc6-f39e-4bc6-99e1-1c026db30f10.jpg)

**Comment by az4521** [comment]
tachiyomi just updated the extlib version to 1.4, tachiAZ still uses 1.3. i'll be fixing this soon™

**Comment by EmnMtz** [comment]
Noted on that. Thank you for the quick response.

**Comment by Start38** [comment]
> tachiyomi baru saja memperbarui versi extlib ke 1.4, tachiAZ masih menggunakan 1.3. saya akan segera memperbaikinya™

Waiting for the repair👍

**Comment by az4521** [comment]
fixed in dev now, i'll be doing an update soon
