### ISSUE TITLE
[Bug] No Luscious extension settings

### ISSUE THREAD

**Issue by Karelftw** [az4521/TachiyomiAZ#72]
I acknowledge that:

- I have updated to the latest version of the app (stable is v8.7.0)
- I have updated all extensions
- If this is an issue with an extension, that I should be opening an issue in https://github.com/inorichi/tachiyomi-extensions

---

### Device information
* Tachiyomi version: 8.7.4-az
* Android version: 13
* Device: Samsung s22 ultra

## Steps to reproduce
1. Install Luscious
2. Go to extensions
3. Go to details of Luscious

### Expected behavior
There should be an option to merge chapter

### Actual behavior
No settings can be found

### Other details
On the main tachiyomi app this is fixable and this issue is related to https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9422#issuecomment-944928050

**Comment by az4521** [comment]
i think i accidentally fixed this at some point, closing
