### ISSUE TITLE
[Bug] Global Search Crash the app

### ISSUE THREAD

**Issue by lan23333** [az4521/TachiyomiAZ#79]
### Device information
* Tachiyomi version: 8.7.4-AZ
* Android version: 14.0.3.0
* Device: XiaoMi 10 Pro

## Steps to reproduce
Do a global search

### Expected behavior
Searches all sources

### Actual behavior
App crashed

### Other details
Crash Log:
[tachiyomi_crash_logs.txt](https://github.com/az4521/TachiyomiAZ/files/11567276/tachiyomi_crash_logs.txt)

**Comment by az4521** [comment]
this has been fixed in dev, and will be fixed in the next release. It was due to an extension crashing due to missing functions in an outdated version of okhttp.
