### ISSUE TITLE
[Bug] Automatic Backups Does Not Delete Old Files

### ISSUE THREAD

**Issue by FHTgames** [az4521/TachiyomiAZ#81]
### Device information
* Tachiyomi version: `v8.7.4-AZ`
* Build time: `2023-02-13 00:48`
* Android version: `9`
* Device: `SM-J701M`

## Steps to reproduce
1. Set **Automatic backups** to Daily.
2. Have **Maximum backups** set to any number.
3. Have your **Backup location** set to anywhere other than the default location.

### Expected behavior
When the app does the automatic backup and reaches the number of maximum backups, it should delete the oldest one and create a new one.

### Actual behavior
The app does not respect the maximum number of backups and does not delete the old files. It does—however— create the new backup.

### Other details
I checked if it was something to do with storage permissions, but that doesn’t seem to be the case. I downloaded a test chapter and was able to save it and then delete it within the app without problem.

This bug leads to have an increasingly high number of `.proto.gz` files in storage (I had over 150 files) without realizing the issue is happening, as the app does not give you any error or notification about automatic backups.

**Comment by az4521** [comment]
fixed in dev build, fix will be in the next release.
