### ISSUE TITLE
[Bug] App crash on migration seems to be duplicate

### ISSUE THREAD

**Issue by coff33ninja** [az4521/TachiyomiAZ#82]
Every time I try to migrate any manga the app keeps on crashing

### Device information
* Tachiyomi version: 8.7.4-AZ
* Android version: MIUI GLOBAL 14.0.1
* Device: Xiaomi-Redmi-Note-12-Pro 

## Steps to reproduce
1. Try to migrate any manga with or without updated sources.

### Expected behavior
Manga migrating from different sources.

### Actual behavior
Application crashes and shuts down.

### Other details
I can however update current active manga if available on the sources and add newer manga without issues.

I also update the plugins via J2k for its auto update features.

**Comment by az4521** [comment]
i'm fairly sure this is the same issue as #79 , an ext crashing the app due to outdated okhttp. dev build has the fix and it will be in the next release. closing
