### ISSUE TITLE
[Bug] can't solve 403 with webpage

### ISSUE THREAD

**Issue by Poncow5** [az4521/TachiyomiAZ#84]
### Device information
* Tachiyomi version: v8.7.0 
* Android version: 5.1.1 
* Device: Oppo A37f

## Steps to reproduce
1. Opening the source
2. Open the webpage 

### Expected behavior
Should've been solve the cloudflare and solve the 403 error

### Actual behavior
Instead suddenly error webpage not available 

### Other details
![Screenshot_2023-10-27-11-17-02-60](https://github.com/az4521/TachiyomiAZ/assets/72888366/af13b7a2-7e1f-4771-a82e-d4a437a43cd6)

**Comment by az4521** [comment]
fixed in 8.7.5
