### ISSUE TITLE
[Bug] Hitomi.la cloudflare error that can't be fixed in webview

### ISSUE THREAD

**Issue by Tarumath** [az4521/TachiyomiAZ#87]
### Device information
* Tachiyomi version: 8.8.0-AZ
* Android version: 13
* Device: Galaxy Tab A8 (SM-X200)

## Steps to reproduce
1. Go to explore hitomi.la
2. If error 403, go to webview to pass the cloudflare check

### Expected behavior
Either no error 403 or error fixed by passing cloudflare check in webview

### Actual behavior
Error 403 but the webview doesn't require a cloudflare check

### Other details
Additional details and attachments.
![screengrab-20240115-131009](https://github.com/az4521/TachiyomiAZ/assets/58615469/f9c8cd0e-0351-4db0-aaf9-272940c88c08)
![screengrab-20240115-131018](https://github.com/az4521/TachiyomiAZ/assets/58615469/5ac54f11-ceac-4bed-b8e8-d61aea65d244)

**Comment by az4521** [comment]
yeah the built in hitomi extension is totally busted, as are a lot of other built in exts. I'm probably going to remove them at some point. You can use the hitomi extension from the unofficial ext repo (which also crashes in current release, but that is fixed in the dev build)
