### ISSUE TITLE
Relicense app

### ISSUE THREAD

**Issue by nonproto** [az4521/TachiyomiAZ#88]
The app is currently licensed as Apache-2.0, however since Tachiyomi is shutting down, and code will be pulled from Mihon. The app needs to be licensed appropriately to take MPL2.0 code.

**Comment by az4521** [comment]
https://github.com/mihonapp/mihon/blob/main/LICENSE

mihon is apache 2.0

**Comment by az4521** [comment]
actually turns out mihon says mpl in the readme but Apache in the license file

¯\_ (ツ) _/¯

**Comment by az4521** [comment]
https://github.com/mihonapp/mihon/issues/199#issuecomment-1904513613
