### ISSUE TITLE
[Bug] GIFS don't display properly

### ISSUE THREAD

**Issue by VirtualURL** [az4521/TachiyomiAZ#92]
### Device information
* Tachiyomi version: 8.8.1-AZ
* Android version: 12
* Device: Motorola Edge 20 Lite

## Steps to reproduce
1. Open gallery containing animated gifs
2. Scroll to the animated gif

### Expected behavior
The gif is animated

### Actual behavior
The first frame of the gif is displayed

### Other details
Happens with any gifs I find on exh, didn't happen before the update

**Comment by az4521** [comment]
you're right. just fixed this in the dev build
https://crafty.moe/tachiyomiAZ.apk
